name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Auto-Merge
        uses: peter-evans/dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Specify any additional configuration options here
